export { default as Header } from './Header/Header';
export { default as Hero} from './Hero/Hero';
export { default as Customers } from './Customers/Customers';
export { default as Businesses } from './Businesses/Businesses';
export { default as Payments } from './Payments/Payments';
export { default as Commerce } from './Commerce/Commerce';
export { default as DarkCards } from './DarkCards/DarkCards';
export { default as DevApi } from './DevApi/DevApi';
export { default as GlobalReach } from './GlobalReach/GlobalReach';
export { default as Cl } from './Cl/Cl';
export { default as Footer } from './Footer/Footer';